### ISSUE TITLE
X-Up-Location header should not be sent by default

### ISSUE THREAD

**Issue by triskweline** [adam12/rack-unpoly#3]
The middleware of this gem automatically [echoes the request URL](https://github.com/adam12/rack-unpoly/blob/6c05b2795ea39043f02e3e98b8e5c8572892a707/lib/rack/unpoly/middleware.rb#L49) in an `X-Up-Location` response header. I recommend removing this feature.

Echoing the request URL was needed to detect the final URL after a redirect in legacy browsers, namely Internet Explorer 11. Now that IE11 is finally dead, this is no longer necessary.

Also reflecting the user-controlled request URL can lead to a [Denial of Service issue](https://github.com/unpoly/unpoly-rails/security/advisories/GHSA-m875-3xf6-mf78) in particular server setups.

Thank you for maintaining this package!

**Comment by adam12** [comment]
Thanks. I saw the commit to the Unpoly repo yesterday and was going to ask.
